// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Entity.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QuesttionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("FAQ");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "Yes, it features an IP68 rating, meaning it is dust-tight and water-resistant. You can wear it while washing your hands or during light workouts, but it is not recommended for diving or high-pressure water sports.",
                            QuesttionText = "Is the watch waterproof?"
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "Yes, absolutely. The built-in independent GPS allows you to share your real-time location with family members through the connected mobile app for safety and peace of mind.",
                            QuesttionText = "Can I share GPS location with family?"
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "Our watch uses a next-generation PPG sensor with advanced AI algorithms to filter out noise during movement, ensuring high accuracy throughout your daily activities.",
                            QuesttionText = "How accurate is heart rate tracking?"
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "Yes, it performs continuous monitoring throughout the night. It analyzes your sleep cycles (deep sleep, light sleep) and provides actionable insights to help you improve your recovery.",
                            QuesttionText = "Does it work while sleeping?"
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "With daily usage and continuous monitoring enabled, the battery typically lasts up to 7 days on a single charge. Usage patterns may vary based on GPS and sensor activity.",
                            QuesttionText = "How long does the battery last?"
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "It offers 24/7 heart rate monitoring, sleep cycle analysis, blood oxygen (SpO2) tracking, and an emergency SOS function.",
                            QuesttionText = "What are the main health features of this smartwatch?"
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "It uses a new generation PPG sensor combined with AI noise cancellation to ensure high accuracy, even during intense exercise.",
                            QuesttionText = "How accurate is the heart rate sensor?"
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "Yes, it tracks your sleep stages and provides personalized suggestions to help you recover better.",
                            QuesttionText = "Can this watch help me improve my sleep quality?"
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "Absolutely. It features an independent GPS that allows real-time location sharing with family members.",
                            QuesttionText = "Is the GPS tracking reliable for my child?"
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "The device will trigger an instant alert, and if configured, it can automatically notify your emergency contacts.",
                            QuesttionText = "What should I do if the watch detects an abnormality?"
                        });
                });

            modelBuilder.Entity("backend.Entity.Submit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Submit");
                });
#pragma warning restore 612, 618
        }
    }
}
